FROM lambci/lambda:nodejs8.10
MAINTAINER hugo

USER root

ENV APP_DIR /var/task

WORKDIR $APP_DIR

# COPY requirements.txt .
# COPY bin ./bin
# COPY lib ./lib

# RUN mkdir -p $APP_DIR/lib
# RUN pip install -r requirements.txt -t /var/task/lib
