export default {
  // sidebar enums
  CHANGE: 'CHANGE',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  // weeklyData enums
  ADD_CROSSFILTER_DATA_REQUEST: 'ADD_CROSSFILTER_DATA_REQUEST',
  ADD_CROSSFILTER_DATA_SUCCESS: 'ADD_CROSSFILTER_DATA_SUCCESS',
  ADD_DIMENSION: '@Weekly/ADD_DIMENSION',
  ADD_DATE_HOUR_DIMENSION: '@InteractionLineChart/ADD_DATE_HOUR_DIMENSION',
  ADD_HOUR_DIMENSION: '@HourOfDayChart/ADD_HOUR_DIMENSION',
  ADD_DAY_OF_WEEK_DIMENSION: '@DayOfWeekChart/ADD_DAY_OF_WEEK_DIMENSION',
  DC_CHART_FILTER_KEPLER_DATA: '@ChartTemplate/DC_CHART_FILTER_KEPLER_DATA',
  SMALL_STATS_FILTER_KEPLER_DATA: '@SmallStats/SMALL_STATS_FILTER_KEPLER_DATA',
  KEPLER_MOUNT_ADD_DATA_TO_MAP: '@KeplerAlerts/ADD_DATA_TO_MAP',
  UPDATE_CHART: '@ChartTemplate/UPDATE_CHART',
  // App enums
  ALLOWED_ALERT_TYPES: [
    'ACCIDENT',
    'JAM',
    'HAZARD_ON_ROAD_POT_HOLE',
    'HAZARD_WEATHER_FLOOD',
    'HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT',
  ]
};
